### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (2999,) (3000,) 

### ISSUE THREAD

**Issue by amarjithaa** [nerajbobra/wavelet-based-ecg-compression#2]
When running the program i get this error.

ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_13236/914743393.py in <module>
     32 
     33     #quantize the coefficients. choose the number of bits to quantize based on the PRD
---> 34     num_bits, PRD_tmp = calculate_num_bits(data, coeffs_scaled, binary_map, scaling_factors, do_plot=(i==1))
     35     PRD_avg = PRD_avg + PRD_tmp
     36 

~\AppData\Local\Temp/ipykernel_13236/349910877.py in calculate_num_bits(orig_sig, coeffs_scaled, binary_map, scaling_factors, do_plot)
     29 
     30         #calculate PRD
---> 31         PRD = calculate_PRD(orig_sig, data_reconstructed)
     32         PRD_dict[num_bits] = PRD
     33 

~\AppData\Local\Temp/ipykernel_13236/2916057613.py in calculate_PRD(orig_sig, reconstructed_sig)
      1 def calculate_PRD(orig_sig, reconstructed_sig):
----> 2     num = np.sum((orig_sig - reconstructed_sig)**2)
      3     den = np.sum(orig_sig**2)
      4 
      5     PRD = np.sqrt(num/den)

ValueError: operands could not be broadcast together with shapes (2999,) (3000,)

**Comment by nerajbobra** [comment]
Looks like ix needed to be updated with loc. I pushed an update, it should be working now
